version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: ticketing-postgres
    environment:
      POSTGRES_USER: ticket
      POSTGRES_PASSWORD: ticket
      POSTGRES_DB: ticketing
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  db-data:
